// This is the default configuration file for the Thirst plugin by WaRToG
// If you want to put color

dehydration:
  rate: 360 // In Seconds
  value: 1 // 1 out of 10
hydration:
  value: 4
displaybar:
  refresh-rate: 20 // In ticks
  character-full: "#"
  character-empty: "/"
messages:
  thirst-refill: "&8You have refilled your thirst!"
  now-ignoring: "&8You are now ignoring thirst!"
  no-longer-ignoring: "&8You are no longer ignoring thirst!"
  now-hidden: "&8You can no longer see the thirst!"
  no-longer-hidden: "&8You can see the thirst!"
  permission: "&cYou don't have the permissions to do this!"
effects:
  '1':
  - SLOW:1
  '0':
  - SLOW_DIGGING:1
  - SLOW:1