# This is the default configuration file for the Thirst plugin by WaRToG
# If you want to put colors, use the & symbol

# Dehydration rate is the amount of time (int seconds) before the thirst
# drops by the value
dehydration:
  rate: 10
  value: 1

# Hydration value is the amount of thirst you will gain for drinking a water bottle
hydration:
  value: 6
  
general:
  # If this is set to true, the player can starve to death
  is-deadly: false

# The refresh rate (in ticks) is the amount of time before the thirst bar updates
display:
  # The type must be one of the following : BOSSBAR, ACTIONBAR or SCOREBOARD
  type: ACTIONBAR
  refresh-rate: 20
  action-bar:
    character-full: "#"
    character-empty: "/"
  

# These are the messages displayed by the plugin
messages:
  thirst-refill: "&8You have refilled your thirst!"
  now-ignoring: "&8You are now ignoring thirst!"
  no-longer-ignoring: "&8You are no longer ignoring thirst!"
  now-hidden: "&8You can no longer see the thirst!"
  no-longer-hidden: "&8You can see the thirst!"
  permission: "&cYou don't have the permissions to do this!"

# These are the potion effect added to the player when he reaches a certain amount of thirst
# The name of the effect and the level is separated by ":" without any spaces
# You can find the effect list here : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html
effects:
  '2':
  - SLOW:1
  '0':
  - SLOW_DIGGING:1
  - SLOW:1